Repository Booksly/BOOKSLY-SERVER, pull requests merged in 2024-05, with the labels that each got.

#122 [feat] #98 마감이벤트 설정 등록 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/request/CreateClosingEventRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/CreateClosingEventResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/entity/closeEvent/ClosingEvent.java
  src/main/java/kyonggi/bookslyserver/domain/event/entity/closeEvent/ClosingEventMenu.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventService.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#125 [fix] #99 타임이벤트 등록 기능
  src/main/java/kyonggi/bookslyserver/domain/event/entity/timeEvent/EmployTimeEventSchedule.java
  src/main/java/kyonggi/bookslyserver/domain/event/entity/timeEvent/TimeEvent.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventService.java
Labels: 🐞 FIX

#126 [feat] #123 가게 주인의 타임이벤트 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetTimeEventResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetTimeEventsResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/repository/EmployTimeEventScheduleRepository.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventQueryService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
  src/main/java/kyonggi/bookslyserver/global/error/handler/GlobalExceptionHandler.java
Labels: ✨ FEAT

#116 [feat] #115 가게 직원 조회 기능 작성(가게 주인)
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/EmployeeReadDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#128 [fix] #123 타임이벤트 조회 메소드 추가
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeRepository.java
Labels: 🐞 FIX

#112 Feature/#111 (가게 주인) 가게 상세 조회 기능 작성
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/shop/ShopOwnerDetailReadOneDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Shop.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#130 [fix] #129 Shop엔티티 수정
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Shop.java
Labels: 🐞 FIX

#136 Feature/#135 가게 삭제 api 수정
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/shop/ShopDeleteResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: 🐞 FIX

#137 [feat] #134 마감이벤트 설정 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetClosingEventResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetClosingEventsResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/repository/ClosingEventRepository.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#140 Feature/#138 가게 관련 api 수정
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/ShopCreateRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/shop/ShopOwnerDetailReadOneDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/ShopRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: 🐞 FIX

#149 [feat] #145 직원 일정 달력 날짜 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/GetCalendarDatesResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
Labels: ✨ FEAT

#151 [feat] #150 기간 반복란 선택지 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetAvailableDatesResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventQueryService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#157 [feat] #155 마감이벤트 적용 및 취소 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/request/ApplyClosingEventsRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/ApplyClosingEventsResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/repository/ClosingEventRepository.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/entity/ReservationSchedule.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#159 [feat] #158 마감이벤트 삭제 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/DeleteClosingEventResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/repository/ReservationScheduleRepository.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#162 [feat] #160 타임이벤트 삭제 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/DeleteTimeEventResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/entity/timeEvent/TimeEvent.java
  src/main/java/kyonggi/bookslyserver/domain/event/entity/timeEvent/TimeEventSchedule.java
  src/main/java/kyonggi/bookslyserver/domain/event/repository/TimeEventScheduleRepository.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/entity/ReservationSchedule.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/repository/ReservationScheduleRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Employee/Employee.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#131 Feature/#120 가게메뉴 단일조회 기능 작성
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/MenuApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/menu/MenuReadOneDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#168 [fix] #167 중복 ErrorCode 수정
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: 🐞 FIX

#143 Feature/#142 REST API URL 수정
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/MenuApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
Labels: 🐞 FIX

#165 Feature/#144 가게 이름 조회 기능
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/shop/ReadShopNamesDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/ShopRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#164 Feature/#161 직원 단일 조회 기능
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/EmployeeReadOneDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/EmployeeReadOneMenuDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/EmployeeReadOneWorkScheduleDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
Labels: ✨ FEAT

#172 Feature/#171 직원 전체 조회(예약하기) 기능 작성
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/ReserveEmployeesDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#181 [refactor] #180 마감이벤트 설정 등록 검증 추가
  src/main/java/kyonggi/bookslyserver/domain/event/repository/ClosingEventRepository.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventCommandService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: 🔨 REFACTOR

#185 [fix] #163 타임 이벤트 등록
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/request/CreateLocalTimeEventsRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/request/CreateStringTimeEventsRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/event/validation/annotation/TimeRange.java
  src/main/java/kyonggi/bookslyserver/domain/event/validation/validator/TimeRangeValidator.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeMenuRepository.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: 🔨 REFACTOR, 🐞 FIX

#182 Feature/#175 직원 이름 조회 기능(이벤트 메뉴 등록)
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/EventRegisterEmployeeNamesDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Employee/Employee.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
Labels: ✨ FEAT

#198 [refactor] #196 마감이벤트 설정 등록 시 검증 추가
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeMenuRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: 🔨 REFACTOR

#199 [feat] #186 당일 마감 이벤트 조회
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetTodayClosingEventResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetTodayClosingEventsResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/repository/ClosingEventRepository.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/event/validation/annotation/TimeSlotFormat.java
  src/main/java/kyonggi/bookslyserver/domain/event/validation/validator/TimeRangeValidator.java
  src/main/java/kyonggi/bookslyserver/domain/event/validation/validator/TimeSlotFormatValidator.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/repository/ReservationScheduleRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Shop.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/CategoryRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/ShopRepository.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
  src/main/java/kyonggi/bookslyserver/global/error/handler/GlobalExceptionHandler.java
Labels: ✨ FEAT

#209 [feat] #200 당일 타임 이벤트 조회
  src/main/java/kyonggi/bookslyserver/domain/event/controller/EventController.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetTodayTimeEventResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/dto/response/GetTodayTimeEventsResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/event/repository/TimeEventRepository.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/event/validation/validator/TimeRangeValidator.java
  src/main/java/kyonggi/bookslyserver/domain/event/validation/validator/TimeSlotFormatValidator.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/repository/ReservationScheduleRepository.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/service/ReserveQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
  src/main/java/kyonggi/bookslyserver/global/util/TimeUtil.java
Labels: ✨ FEAT

#210 [feat] #208 LocalTime.MAX로 인한 MYSQL 오류 수정 및 코드 개선
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventQueryService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
Labels: 🔨 REFACTOR, 🐞 FIX

#215 [refactor] #211 타임 이벤트 등록 시 검증 조건 추가
  src/main/java/kyonggi/bookslyserver/domain/event/service/TimeEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeMenuRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeRepository.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
  src/main/java/kyonggi/bookslyserver/global/util/TimeUtil.java
Labels: 🔨 REFACTOR

#193 Feature/#190 Top100가게 조회 기능 작성
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/menu/ReserveEventMenuDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/shop/ShopFilterDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/ShopRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#220 [feat] #219 직원 예약 일정의 이벤트 진행 여부 조회
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/CheckEventStatusResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#189 Feature/#183 직원별 메뉴 조회 기능(이벤트 메뉴 등록)
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/MenuApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/menu/EventRegisterEmployeeMenuDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/menu/EventRegisterMenuNamesDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
Labels: ✨ FEAT

#222 [feat] #216 직원 예약 일정에 진행되는 이벤트 메뉴 조회
  src/main/java/kyonggi/bookslyserver/domain/event/entity/Event.java
  src/main/java/kyonggi/bookslyserver/domain/event/entity/closeEvent/ClosingEvent.java
  src/main/java/kyonggi/bookslyserver/domain/event/entity/timeEvent/TimeEvent.java
  src/main/java/kyonggi/bookslyserver/domain/event/service/ClosingEventCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/EventWithMenusByCategoryResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/GetEventCategoryAndMenus.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/GetEventMenu.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/GetEventMenusResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/EmployeeMenuRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#224 [feat] #223 일반회원 프로필 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetUserProfileResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/entity/User.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserService.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
Labels: ✨ FEAT

#226 [feat] #225 기업회원 프로필 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
  src/main/java/kyonggi/bookslyserver/domain/user/controller/ShopOwnerController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetOwnerProfileResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/repository/ShopOwnerRepository.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/ShopOwnerService.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserService.java
Labels: ✨ FEAT

#229 [feat] #227 일반회원 상세정보 조회 API 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetUserDetailInfoResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserService.java
Labels: ✨ FEAT

#230 [refactor] #228 기업회원 API URI 수정
  src/main/java/kyonggi/bookslyserver/domain/user/controller/ShopOwnerController.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
Labels: 🔨 REFACTOR

#232 [feat] #231 기업회원 상세정보 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/ShopOwnerController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetOwnerDetailInfoResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/ShopOwnerService.java
Labels: ✨ FEAT

#235 [feat] #234 일반회원 정보 업데이트 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/UpdateUserInfoRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/UpdateUserInfoResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/entity/User.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserService.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/validator/VerifyPhoneNumValidator.java
Labels: ✨ FEAT

#237 [feat] #233 기업회원 정보 업데이트 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/ShopOwnerController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/UpdateOwnerInfoRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/UpdateOwnerInfoResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/entity/ShopOwner.java
  src/main/java/kyonggi/bookslyserver/domain/user/entity/User.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/ShopOwnerService.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/validator/CheckPasswordValidator.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#246 [feat] #244 단골 가게 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetFavoriteShopResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetFavoriteShopsResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/repository/FavoriteShopRepository.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserQueryService.java
Labels: ✨ FEAT

#250 Feature/#240 가게 메인 페이지 조회 기능
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/employee/ShopOwnerMainEmployeesDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/menu/ShopOwnerMainMenusDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/shop/ShopOwnerMainReadOneDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#218 Feature/#195 새로 입점한 가게 리스트 조회
  src/main/java/kyonggi/bookslyserver/domain/event/dto/request/CreateTimeEventsRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/EmployeeCreateRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/EmployeeWorkScheduleDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/MenuCategoryCreateDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/MenuCreateRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/ShopCreateRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/shop/NewShopFilterDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Shop.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/ShopRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#252 [feat] #247 리뷰 등록 기능 구현
  build.gradle
  src/main/java/kyonggi/bookslyserver/domain/reservation/entity/Reservation.java
  src/main/java/kyonggi/bookslyserver/domain/review/controller/ReviewController.java
  src/main/java/kyonggi/bookslyserver/domain/review/dto/request/CreateReviewRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/review/dto/response/CreateReviewResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/review/entity/Review.java
  src/main/java/kyonggi/bookslyserver/domain/review/repository/ReviewImageRepository.java
  src/main/java/kyonggi/bookslyserver/domain/review/service/ReviewService.java
  src/main/java/kyonggi/bookslyserver/global/auth/handelr/OAuthAuthenticationSuccessHandler.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/user/UserId.java
  src/main/java/kyonggi/bookslyserver/global/aws/s3/AmazonS3Manager.java
  src/main/java/kyonggi/bookslyserver/global/common/Uuid.java
  src/main/java/kyonggi/bookslyserver/global/common/UuidRepository.java
  src/main/java/kyonggi/bookslyserver/global/config/AmazonConfig.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
  src/main/java/kyonggi/bookslyserver/global/config/SwaggerConfig.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#254 [feat] #253 일반회원 리뷰 조회
  src/main/java/kyonggi/bookslyserver/domain/review/controller/ReviewController.java
  src/main/java/kyonggi/bookslyserver/domain/review/dto/response/GetUserReviewResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/review/entity/Review.java
  src/main/java/kyonggi/bookslyserver/domain/review/service/ReviewService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#256 [feat] #255 리뷰 삭제 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/reservation/entity/Reservation.java
  src/main/java/kyonggi/bookslyserver/domain/review/controller/ReviewController.java
  src/main/java/kyonggi/bookslyserver/domain/review/entity/Review.java
  src/main/java/kyonggi/bookslyserver/domain/review/service/ReviewService.java
  src/main/java/kyonggi/bookslyserver/global/aws/s3/AmazonS3Manager.java
Labels: ✨ FEAT

#261 [chore] #260 접근 허용/비허용 url 수정
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
Labels: ⚙ CHORE
