Repository Booksly/BOOKSLY-SERVER, pull requests merged in 2024-04, with the labels that each got.

#22 [fix] #21 redis 환경변수 접근 이름 오류 수정
  src/main/java/kyonggi/bookslyserver/global/config/RedisConfig.java
Labels: 🐞 FIX

#25 [feat] 기업회원 입력 인증코드 진위 확인 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserAuthController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/OwnerVerifyRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/OwnerVerifyResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserAuthService.java
  src/main/java/kyonggi/bookslyserver/global/util/RedisUtil.java
Labels: ✨ FEAT

#28 [feat] 일반회원 입력 인증코드 진위 확인
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserAuthController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/VerifyCodeRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/VerifyCodeResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/entity/User.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserAuthService.java
Labels: ✨ FEAT

#32 [feat] #31 접근 허용 uri 설정 수정
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
Labels: ✨ FEAT

#34 [refactor] #33 일부 필드를 상수로 변경
  src/main/java/kyonggi/bookslyserver/global/auth/handelr/OAuthAuthenticationSuccessHandler.java
  src/main/java/kyonggi/bookslyserver/global/auth/jwt/ExceptionHandlerFilter.java
  src/main/java/kyonggi/bookslyserver/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/kyonggi/bookslyserver/global/auth/jwt/JwtProvider.java
  src/main/java/kyonggi/bookslyserver/global/util/AuthUtil.java
  src/main/java/kyonggi/bookslyserver/global/util/RedisUtil.java
Labels: 🔨 REFACTOR

#35 [refactor] #30 에러 응답 형식 수정
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/SendSMSRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/VerifyCodeRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/VerifyPhoneNum.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/validator/VerifyPhoneNumValidator.java
  src/main/java/kyonggi/bookslyserver/global/auth/handelr/CustomAccessDeniedHandler.java
  src/main/java/kyonggi/bookslyserver/global/auth/handelr/CustomAuthenticationEntryPoint.java
  src/main/java/kyonggi/bookslyserver/global/auth/jwt/ExceptionHandlerFilter.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
  src/main/java/kyonggi/bookslyserver/global/error/BaseErrorCode.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
  src/main/java/kyonggi/bookslyserver/global/error/dto/ErrorResponse.java
  src/main/java/kyonggi/bookslyserver/global/error/dto/ErrorResponseDto.java
  src/main/java/kyonggi/bookslyserver/global/error/dto/FieldErrorResponseDto.java
  src/main/java/kyonggi/bookslyserver/global/error/handler/GlobalExceptionHandler.java
Labels: 🔨 REFACTOR

#37 [feat] #10 기업회원의 회원가입
  src/main/java/kyonggi/bookslyserver/domain/user/controller/ShopOwnerController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/JoinOwnerRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/JoinOwnerResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/entity/ShopOwner.java
  src/main/java/kyonggi/bookslyserver/domain/user/repository/ShopOwnerRepository.java
  src/main/java/kyonggi/bookslyserver/domain/user/repository/UserRepository.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/ShopOwnerService.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/CheckLoginIdFormat.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/CheckPasswordStrength.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/NotFalse.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/validator/CheckLoginIdFormatValidator.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/validator/CheckPasswordValidator.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/validator/NotFalseValidator.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/validator/VerifyPhoneNumValidator.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
Labels: ✨ FEAT

#41 [feat] #38 가게 등록 api 작성
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/BusinessScheduleDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/ShopCreateRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/response/ShopCreateResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Address.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Category.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Shop.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/TimeUnit.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/BusinessScheduleRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/ShopImageRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/ShopRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#46 Feature/#43 가게 정보 수정 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/ShopCreateRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/BusinessSchedule/BusinessSchedule.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Address.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Category.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Shop.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/ShopImage.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
Labels: ✨ FEAT

#50 [feat] #48 API URL 수정
  src/main/java/kyonggi/bookslyserver/domain/user/controller/ShopOwnerController.java
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserAuthController.java
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserVerifyController.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/CheckLoginIdFormat.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/CheckPasswordStrength.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/NotFalse.java
  src/main/java/kyonggi/bookslyserver/domain/user/validation/annotation/VerifyPhoneNum.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
Labels: 🔨 REFACTOR

#59 [feat] #39 기업회원 로그인 구현
  src/main/java/kyonggi/bookslyserver/domain/reservation/controller/ShopOwnerReserveController.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/converter/ReservationConverter.java
  src/main/java/kyonggi/bookslyserver/domain/reservation/service/ReserveCommandService.java
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/ShopApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/ShopService.java
  src/main/java/kyonggi/bookslyserver/domain/user/controller/ShopOwnerController.java
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserController.java
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserVerifyController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/request/ShopOwnerLoginRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/entity/ShopOwner.java
  src/main/java/kyonggi/bookslyserver/domain/user/repository/ShopOwnerRepository.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/ShopOwnerService.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserService.java
  src/main/java/kyonggi/bookslyserver/global/auth/handelr/CustomAuthenticationFailureHandler.java
  src/main/java/kyonggi/bookslyserver/global/auth/handelr/CustomAuthenticationSuccessHandler.java
  src/main/java/kyonggi/bookslyserver/global/auth/handelr/OAuthAuthenticationSuccessHandler.java
  src/main/java/kyonggi/bookslyserver/global/auth/jwt/IdPasswordAuthenticationFilter.java
  src/main/java/kyonggi/bookslyserver/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/shopOwner/OwnerId.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/shopOwner/OwnerIdArgumentResolver.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/shopOwner/OwnerPrincipalDetails.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/shopOwner/OwnerPrincipalService.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/user/OAuthPrincipalDetails.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/user/OAuthPrincipalService.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/user/UserId.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/user/UserIdArgumentResolver.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/user/userInfo/OAuth2UserInfo.java
  src/main/java/kyonggi/bookslyserver/global/auth/principal/user/userInfo/OAuthAttributes.java
  src/main/java/kyonggi/bookslyserver/global/config/PasswordEncoderConfig.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
  src/main/java/kyonggi/bookslyserver/global/config/WebConfig.java
  src/main/java/kyonggi/bookslyserver/global/error/ErrorCode.java
  src/main/java/kyonggi/bookslyserver/global/util/JwtUtil.java
Labels: ✨ FEAT

#82 [feat] #81 본인인증 여부 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserVerifyController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/CheckVerificationStatusResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserAuthService.java
Labels: ✨ FEAT

#83 Feature/#80 가게 직원 등록 기능
  src/main/java/kyonggi/bookslyserver/domain/shop/controller/EmployeeApiController.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/EmployeeCreateRequestDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/dto/request/EmployeeWorkScheduleDto.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Employee/Employee.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Employee/EmployeeMenu.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Employee/WorkSchedule.java
  src/main/java/kyonggi/bookslyserver/domain/shop/entity/Shop/Shop.java
  src/main/java/kyonggi/bookslyserver/domain/shop/repository/MenuRepository.java
  src/main/java/kyonggi/bookslyserver/domain/shop/service/EmployeeService.java
Labels: ✨ FEAT

#95 [feat] #94 일반회원 닉네임 조회 기능 구현
  src/main/java/kyonggi/bookslyserver/domain/user/controller/UserController.java
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetUserNicknameResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/UserService.java
  src/main/java/kyonggi/bookslyserver/global/config/SecurityConfig.java
Labels: ✨ FEAT

#97 [refactor] #86 dto 생성 방식 수정
  src/main/java/kyonggi/bookslyserver/domain/user/dto/response/GetOwnerLoginIdResponseDto.java
  src/main/java/kyonggi/bookslyserver/domain/user/service/ShopOwnerService.java
Labels: 🔨 REFACTOR
